from fastapi import APIRouter
from app.api.v1 import auth, users, addons, versions, payments, admin, tickets, profiles, analytics, tags, organizations, automation, api_keys, stars, reviews, notifications, collaborators, security
from app.api.v1 import auth, users, addons, versions, payments, admin, tickets, profiles, analytics, tags, organizations, automation, api_keys, stars, reviews, notifications, collaborators, rollouts, feature_flags
from app.api.v1 import auth, users, addons, versions, payments, admin, tickets, profiles, analytics, tags, organizations, automation, api_keys, stars, reviews, notifications, collaborators, webhooks

router = APIRouter(prefix="/v1")

router.include_router(auth.router)
router.include_router(users.router)
router.include_router(profiles.router)
router.include_router(addons.router)
router.include_router(versions.router)
router.include_router(analytics.router)
router.include_router(payments.router)
router.include_router(admin.router)
router.include_router(tickets.router)
router.include_router(tags.router)
router.include_router(organizations.router)
router.include_router(automation.router)
router.include_router(api_keys.router)
router.include_router(stars.router)
router.include_router(reviews.router)
router.include_router(notifications.router)
router.include_router(collaborators.router)
router.include_router(collaborators.transfer_router)
router.include_router(collaborators.invitation_router)
router.include_router(security.signing_router)
router.include_router(security.sig_router)
router.include_router(security.scan_router)
router.include_router(security.sbom_router)
router.include_router(security.ip_router)
router.include_router(security.twofa_router)
router.include_router(rollouts.router)
router.include_router(feature_flags.router)
router.include_router(webhooks.router)
